const JOBLIST = [
  {
    key: 0,
    date: "8/19/21",
    employer: "Apple",
    position: "Front-End Developer",
    jobSource: "LinkedIn",
    url: "http://www.linkedin.com",
    status: "applied",
    applied: true,
    employerResponse: "",
    notes: "Follow up in a week for code test.",
  },
  {
    key: 1,
    date: "8/18/21",
    employer: "Microsoft",
    position: "Junior Front-End Developer",
    jobSource: "Dice Careers",
    url: "http://www.dice.com",
    status: "saved",
    applied: false,
    employerResponse: "",
    notes: "Code test due on 9/1/21",
  },
  {
    key: 2,
    date: "8/16/21",
    employer: "Netflix",
    position: "Front-End Apprentice",
    jobSource: "Indeed",
    url: "http://www.indeed.com",
    status: "applied",
    applied: true,
    employerResponse: "",
    notes: "Brush up on APIs",
  },
];

export default JOBLIST;